# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1dd6d3c122c35a7d98619646b634fc5222cd8bde0fc6e613b896a4a10c278afc58f9122e11a3fd497294989a6194e50fb111e8fa28c5be7b37f011969be12714

test:
  secret_key_base: e18e59874380afd4de430526dc70a58dd24969ad91d0d8f1988c0880b5d933787b0969a475410268dd95fd927a2e0169f4918751b160e1b948d2f1fe758497b4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
